### PR TITLE
Vibrancy

### PR DESCRIPTION
**Pull request by evanmiller**
* New `contentInsets` property behaves like that of [NSScrollView](https://developer.apple.com/documentation/appkit/nsscrollview/1403461-contentinsets?language=objc) - Table Grids will "scroll under" adjacent NSVisualEffectViews for a vibrancy effect. Headers / footers are placed inside the `contentInsets`.

* Header and footer corners (top-left and bottom-left) now use a vibrant `NSVisualEffectView` that the row / column header will appear to scroll under

* Sample project uses a vibrant bottom control view

* Marking WIP because this new code requires 10.10 Yosemite or later (and likely clashes with the other open PRs)

### CODE REVIEW

**Comment by evanmiller** [comment]
If you're comfortable with the 10.10 requirement, this pull request is ready to go.

**Comment by pixelspark** [comment]
10.10 is fine with me! merged :+1:

**Comment by evanmiller** [comment]
Thanks for getting through all these PRs. I'll have one more for the last open issue. Then hopefully some peace and quiet around here!

**Comment by pixelspark** [comment]
Good work @evanmiller. Curious to see how you’re using this!

**Pull request merged**
