### PR TITLE
Improve selection performance

### PR DESCRIPTION
**Pull request by DivineDominion**
This is work in progress, but I want to open this for discussion as early as possible (since I may miss something :))
- [x] make selection change on mouse click more performant
- [ ] ~get rid of double redrawing: in both `moveX` `NSResponder` callbacks and in selection index setters redrawing is triggered~
- [x] fix scroll wrapping: when pressing left arrow key in column 0, the scroll view wraps to the last column but left-aligned (instead of at the right edge)

---

Optimization task for another PR:

```
- [ ] get rid of double redrawing: in both `moveX` `NSResponder` callbacks and in selection index setters redrawing is triggered
```

### CODE REVIEW

**Comment by pixelspark** [comment]
@DivineDominion good work! This works just fine in the app I am using MBTableGrid for. Just let me know when you feel this is ready for merging.

**Comment by DivineDominion** [comment]
Thanks! Clicking is still slow, and I'd have to fix the weird wrapp-and-scroll behavior first before I can use it in my app. Do you have suggestions where the scrolling bug may stem from?

**Comment by pixelspark** [comment]
No clue - I might have a look later on. If I find something I'll let you know!

**Comment by DivineDominion** [comment]
Am working on this again. NSTableView just doesn't cut it :)

**Comment by DivineDominion** [comment]
Ok, that was it, I think. Please have a look at the new changes. In the demo app, when you resized the window so that you had to scroll horizontally, selection wrapping to the next row didn't display correctly. That should be fixed now! If you don't find anything, I think it's ready to merge & then move on.

**Comment by pixelspark** [comment]
@DivineDominion very cool! Will have a look at this later on 😃

**Comment by fearofcode** [comment]
Is there any information on what causes the slow clicking behavior mentioned above? Apologies if it is inappropriate to comment on a pull request that has been inactive for a long time.

**Comment by DivineDominion** [comment]
I don't remember the cause 😬 But merging the WIP would still be cool. The open task could be tackled separately. (I'm not working on tables this year anymore, and leaving the PR around for longer sounds like a bad idea.)

**Comment by DivineDominion** [comment]
@pixelspark forgot to ping you, sorry :)

**Pull request merged**
